package Homework2023.RPat;


import java.awt.Dimension;
import java.awt.Point;

import BridgeSegment.AbstractBridgeSystem;
import simView.ViewableComponent;


public class BridgeSystem extends AbstractBridgeSystem {
		
	
	
	

	String b1Phase, b2Phase, b3Phase;	
	
	
	
	//BridgeSystem ref=new BridgeSystem("bridge");
	
	public BridgeSystem() {
		this("Bridge System");
	}
	public BridgeSystem(String name) {
		super(name);
		bridgeSystemConstruct();
	}

	public void bridgeSystemConstruct() {
	
		
		if(AbstractBridgeSystem.BridgeSystemSetting.Bridge1InitialState == AbstractBridgeSystem.BridgeState.WEST_TO_EAST) {
			b1Phase = "WEST_GREEN";
		}
		else 
		{
			b1Phase = "EAST_GREEN";
		}
		
		if(AbstractBridgeSystem.BridgeSystemSetting.Bridge2InitialState == AbstractBridgeSystem.BridgeState.WEST_TO_EAST) {
			b2Phase = "WEST_GREEN";
		}
		else
		{
			b2Phase = "EAST_GREEN";
		}
		
		if
		(AbstractBridgeSystem.BridgeSystemSetting.Bridge3InitialState == AbstractBridgeSystem.BridgeState.WEST_TO_EAST) {
			b3Phase = "WEST_GREEN";
		}else 
		{
			b3Phase = "EAST_GREEN";
		}

	
		this.addInport("eastbound_in");
		this.addInport("westbound_out");
		
		this.addOutport("eastbound_out");
		this.addOutport("westbound_in");


	
		
	
	
		BridgeSegment bridgeSegment1 = new BridgeSegment("bridgeSegment1", b1Phase, AbstractBridgeSystem.BridgeSystemSetting.Bridge1TrafficLightDurationTime);
		BridgeSegment bridgeSegment2 = new BridgeSegment("bridgeSegment2", b2Phase, AbstractBridgeSystem.BridgeSystemSetting.Bridge2TrafficLightDurationTime);
		BridgeSegment bridgeSegment3 = new BridgeSegment("bridgeSegment3", b3Phase, AbstractBridgeSystem.BridgeSystemSetting.Bridge3TrafficLightDurationTime);

	
	add(this.westCarGenerator);
	add(this.eastCarGenerator);
	add(this.transduser);
	add(bridgeSegment1);
	add(bridgeSegment2);
	add(bridgeSegment3);
	addCoupling(bridgeSegment3, "west_out",bridgeSegment2,"west_in");
	addCoupling(bridgeSegment1, "east_out",bridgeSegment2,"east_in");
	addCoupling(bridgeSegment2, "west_out",bridgeSegment1,"west_in");
	addCoupling(bridgeSegment2, "east_out",bridgeSegment3,"east_in");
	//addCoupling(this.ref, "eastbound_out",bridgeSegment1, "west_out");
	//addCoupling(this.ref, "westbound_out",bridgeSegment3, "east_out");
	addCoupling(this,"eastbound_in",westCarGenerator,"in");
	addCoupling(this,"westbound_in",eastCarGenerator,"in");
	addCoupling(this,"eastbound_out",bridgeSegment1,"west_out");
	addCoupling(this,"westbound_out",bridgeSegment3,"east_out");
	






	
	addCoupling(westCarGenerator,"out",bridgeSegment3,"west_in");
	addCoupling(eastCarGenerator,"out",bridgeSegment1,"east_in");
	addCoupling(bridgeSegment1, "east_out", this.transduser, "Bridge1_EastOut"); 
	addCoupling(bridgeSegment1, "west_out", this.transduser, "Bridge1_WestOut"); 
	addCoupling(bridgeSegment2, "east_out", this.transduser, "Bridge2_EastOut"); 
	addCoupling(bridgeSegment2, "west_out", this.transduser, "Bridge2_WestOut"); 
	addCoupling(bridgeSegment3, "east_out", this.transduser, "Bridge3_EastOut"); 
	addCoupling(bridgeSegment3, "west_out", this.transduser, "Bridge3_WestOut"); 
	
	

	
		
	}
    /**
     * Automatically generated by the SimView program.
     * Do not edit this manually, as such changes will get overwritten.
     */
   
    /**
     * Automatically generated by the SimView program.
     * Do not edit this manually, as such changes will get overwritten.
     */
    public void layoutForSimView()
    {
        preferredSize = new Dimension(1456, 616);
        if((ViewableComponent)withName("bridgeSegment3")!=null)
             ((ViewableComponent)withName("bridgeSegment3")).setPreferredLocation(new Point(201, 475));
        if((ViewableComponent)withName("EastGen")!=null)
             ((ViewableComponent)withName("EastGen")).setPreferredLocation(new Point(839, 443));
        if((ViewableComponent)withName("Transducer")!=null)
             ((ViewableComponent)withName("Transducer")).setPreferredLocation(new Point(8, 22));
        if((ViewableComponent)withName("bridgeSegment1")!=null)
             ((ViewableComponent)withName("bridgeSegment1")).setPreferredLocation(new Point(724, 196));
        if((ViewableComponent)withName("WestGen")!=null)
             ((ViewableComponent)withName("WestGen")).setPreferredLocation(new Point(-17, 326));
        if((ViewableComponent)withName("bridgeSegment2")!=null)
             ((ViewableComponent)withName("bridgeSegment2")).setPreferredLocation(new Point(432, 335));
    }
}
	//public static void main(String[] args) {
		//new BridgeSystem();

    /**
     * Automatically generated by the SimView program.
     * Do not edit this manually, as such changes will get overwritten.
     */
    
    
   //**
   
   

